---
- name: Install Docker
  hosts: all
  become: yes  # This allows Ansible to use sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure current user can run Docker commands
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes