- name: Setup GitLab Runner
  hosts: kezan
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - openssh-server
        - ca-certificates
        - postfix

    - name: Add GitLab Runner repository
      apt_repository:
        repo: "deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ xenial main"
        state: present
        filename: 'gitlab-runner'
        update_cache: yes

    - name: Install GitLab Runner
      apt:
        name: gitlab-runner
        state: present

    - name: Load GitLab token from arcturis.yaml
      include_vars:
        file: arcturis.yaml
        name: gitlab_token_vars

    - name: Register GitLab Runner
      command: |
        gitlab-runner register \
          --non-interactive \
          --url "https://gitlab.com/" \
          --registration-token "{{ gitlab_token_vars.gitlab_token }}" \
          --executor "shell" \
          --description "My GitLab Runner"

    - name: Start GitLab Runner
      service:
        name: gitlab-runner
        state: started
        enabled: yes
