---
- name: Setup GitLab
  hosts: kezan
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - openssh-server
        - ca-certificates
        - postfix

    - name: Add GitLab repository
      apt_repository:
        repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main"
        state: present
        filename: 'gitlab-ce'
        update_cache: yes

    - name: Install GitLab
      apt:
        name: gitlab-ce
        state: present

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure
