---
- name: Configure repo
  hosts: kezan
  become: yes
  vars:
    github_repo_url: "https://github.com/Andrew-Dupere/demotraders.git"
    deploy_directory: "/home/ubuntu/kezan/apps/demotraders"

  tasks:
    - name: Create Demo Traders Directory
      file:
        path: "{{ deploy_directory }}"
        state: directory
        mode: "0755"  # Set the permissions as needed

    - name: Install Git
      apt:
        name: git
        state: present  # Ensure that Git is installed

    - name: Clone GitHub Repository
      git:
        repo: "{{ github_repo_url }}"
        dest: "{{ deploy_directory }}"
        clone: yes
        update: yes  # Ensure that the repository is up to date
        
    - name: Configure Git safe.directory
      command: git config --global --add safe.directory /home/ubuntu/kezan/apps/demotraders
      become: yes
