---

#please add packages required for running selenium firefox bots

- name: kezan config
  hosts: kezan
  become: true  # Run tasks with sudo (root) privileges

  tasks:
  - name: OS PACKAGES
    block:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Optional: only update cache if older than 1 hour

    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install python3.10-venv
      apt:
        name: python3.10-venv
        state: present
      become: yes  # Ensure you have the permissions to install packages
    tags: [ 'os_packages' ]

  - name: PYTHON PACKAGES
    block:
    - name: Install Gunicorn with pip
      pip:
        name: gunicorn
        state: present

    tags: [ 'python_packages' ]
